name: build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true

      - name: Install dependencies
        run: go get -v .

      - name: Run tests
        run: go test -v ./ ...

      - name: Build
        run: go build -v main.go
